runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /images
  static_dir: images
  
- url: /(index(\.html)?)?
  static_files: static/index.html
  http_headers:
    Access-Control-Allow-Origin: "*"
  upload: static/index.html
